// <auto-generated />
using CursoAngularDotNet_WebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursoAngularDotNet_WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("CursoAngularDotNet_WebAPI.Departamento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("sigla")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nome = "Tecnologia",
                            sigla = "TI"
                        },
                        new
                        {
                            id = 2,
                            nome = "Recursos Humanos",
                            sigla = "RH"
                        },
                        new
                        {
                            id = 3,
                            nome = "Administrativo",
                            sigla = "ADM"
                        },
                        new
                        {
                            id = 4,
                            nome = "Financeiro",
                            sigla = "FIN"
                        },
                        new
                        {
                            id = 5,
                            nome = "Comercial",
                            sigla = "COM"
                        });
                });

            modelBuilder.Entity("CursoAngularDotNet_WebAPI.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("foto")
                        .HasColumnType("TEXT");

                    b.Property<int>("iddepartamento")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("rg")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            foto = "foto",
                            iddepartamento = 3,
                            nome = "Luiz",
                            rg = "54226987-4"
                        },
                        new
                        {
                            id = 2,
                            foto = "foto",
                            iddepartamento = 1,
                            nome = "Frederico",
                            rg = "12226987-4"
                        },
                        new
                        {
                            id = 3,
                            foto = "foto",
                            iddepartamento = 1,
                            nome = "Santos",
                            rg = "55226955-4"
                        },
                        new
                        {
                            id = 4,
                            foto = "foto",
                            iddepartamento = 2,
                            nome = "Queiroz",
                            rg = "55255987-4"
                        },
                        new
                        {
                            id = 5,
                            foto = "foto",
                            iddepartamento = 4,
                            nome = "Junior",
                            rg = "51126987-4"
                        },
                        new
                        {
                            id = 6,
                            foto = "foto",
                            iddepartamento = 5,
                            nome = "Luiza",
                            rg = "32226987-4"
                        },
                        new
                        {
                            id = 7,
                            foto = "foto",
                            iddepartamento = 2,
                            nome = "Margarida",
                            rg = "55224387-4"
                        },
                        new
                        {
                            id = 8,
                            foto = "foto",
                            iddepartamento = 1,
                            nome = "Larissa",
                            rg = "30226987-4"
                        },
                        new
                        {
                            id = 9,
                            foto = "foto",
                            iddepartamento = 1,
                            nome = "João",
                            rg = "50126987-4"
                        },
                        new
                        {
                            id = 10,
                            foto = "foto",
                            iddepartamento = 6,
                            nome = "Arthur",
                            rg = "52269877-4"
                        },
                        new
                        {
                            id = 11,
                            foto = "foto",
                            iddepartamento = 7,
                            nome = "Iago",
                            rg = "99226987-4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
